/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppWithdrawRouteImport } from './routes/app.withdraw'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppReferralRouteImport } from './routes/app.referral'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppEarnRouteImport } from './routes/app.earn'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEarnRoute = AppEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AppRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/earn': typeof AppEarnRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/earn': typeof AppEarnRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/earn': typeof AppEarnRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/announcements'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/earn'
    | '/app/history'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/referral'
    | '/app/tasks'
    | '/app/withdraw'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/announcements'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/earn'
    | '/app/history'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/referral'
    | '/app/tasks'
    | '/app/withdraw'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/announcements'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/earn'
    | '/app/history'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/referral'
    | '/app/tasks'
    | '/app/withdraw'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/earn': {
      id: '/app/earn'
      path: '/earn'
      fullPath: '/app/earn'
      preLoaderRoute: typeof AppEarnRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppEarnRoute: typeof AppEarnRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralRoute: typeof AppReferralRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEarnRoute: AppEarnRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralRoute: AppReferralRoute,
  AppTasksRoute: AppTasksRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
