/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWithdrawRouteImport } from './routes/app.withdraw'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppReferralRouteImport } from './routes/app.referral'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppEarnRouteImport } from './routes/app.earn'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEarnRoute = AppEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/earn': typeof AppEarnRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/earn': typeof AppEarnRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/earn': typeof AppEarnRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/earn'
    | '/app/history'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/referral'
    | '/app/tasks'
    | '/app/withdraw'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/earn'
    | '/app/history'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/referral'
    | '/app/tasks'
    | '/app/withdraw'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/earn'
    | '/app/history'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/referral'
    | '/app/tasks'
    | '/app/withdraw'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/earn': {
      id: '/app/earn'
      path: '/earn'
      fullPath: '/app/earn'
      preLoaderRoute: typeof AppEarnRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEarnRoute: typeof AppEarnRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralRoute: typeof AppReferralRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEarnRoute: AppEarnRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralRoute: AppReferralRoute,
  AppTasksRoute: AppTasksRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
